restaurant/Controllers/ApercusController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using restaurant.Data;
using restaurant.Models;

namespace restaurant.Controllers
{
    public class ApercusController : Controller
    {
        private readonly AppDbContext _context;

        public ApercusController(AppDbContext context)
        {
            _context = context;
            
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.TotalCommandes= await _context.Commandes.Where(e=>e.Statut.Equals("Terminer")).SumAsync(e=>e.Total);
            ViewBag.NumberCommandes = await _context.Commandes.CountAsync();
            ViewBag.NumberReservation = await _context.BookingTables.CountAsync();
            ViewBag.NumberPlat = await _context.Plats.CountAsync();
            return View();
        }
    }
}

restaurant/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using restaurant.Data;
using restaurant.Models;
namespace restaurant.Controllers
{
    public class MenuController : Controller
    {

        private readonly AppDbContext _context;

        public MenuController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _context.Plats.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plat = await _context.Plats.Include(p => p.PlatIngredients).ThenInclude(pi => pi.Ingredient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plat == null)
            {
                return NotFound();
            }

            return View(plat);
        }
    }
}

restaurant/Controllers/PlatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using restaurant.Data;
using restaurant.Models;

namespace restaurant.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PlatsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly string _imageDirectory = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");

        public PlatsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Plats
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.Plats.ToListAsync());
        }

        // GET: Plats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var plat = await _context.Plats.Include(p => p.PlatIngredients).ThenInclude(pi=> pi.Ingredient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plat == null)
            {
                return NotFound();
            }

            return View(plat);
        }

        // GET: Plats/Create
        public async Task<IActionResult> Create()
        {
            ViewData["Ingredients"] = new SelectList(await _context.Ingredients.ToListAsync(), "Id", "Name");
            var plat = new Plat();

            return View(plat);
        }

        // POST: Plats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,IngredientIds")] Plat plat, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string imagePath = null;

                if (file != null && file.Length > 0)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    imagePath = Path.Combine("images", fileName);
                    string fullPath = Path.Combine(_imageDirectory, fileName);

                    if (!Directory.Exists(_imageDirectory))
                    {
                        Directory.CreateDirectory(_imageDirectory);
                    }

                    using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    plat.ImagePath = imagePath;
                }
                _context.Add(plat);
                await _context.SaveChangesAsync();  
                foreach (var ingredientId in plat.IngredientIds)
                {
                    var platIngredient = new PlatIngredient
                    {
                        PlatId = plat.Id,  
                        IngredientId = ingredientId,
                        Quantity = 1
                    };
                    _context.PlatIngredients.Add(platIngredient);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Ingredients"] = new SelectList(await _context.Ingredients.ToListAsync(), "Id", "Name");
            return View(plat);
        }


        // GET: Plats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["Ingredients"] = new SelectList(await _context.Ingredients.ToListAsync(), "Id", "Name");
            var plat = await _context.Plats.FindAsync(id);
            if (plat == null)
            {
                return NotFound();
            }
            return View(plat);
        }

        // POST: Plats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,IngredientIds")] Plat plat, IFormFile? file)
        {
            if (id != plat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string imagePath = null;

                    if(file != null && file.Length > 0){
                        string fileName = Path.GetFileName(file.FileName);
                         imagePath = Path.Combine("images", fileName);
                        string fullPath = Path.Combine(_imageDirectory, fileName);

                        if (!Directory.Exists(_imageDirectory))
                        {
                            Directory.CreateDirectory(_imageDirectory);
                        }

                        using (var stream = new FileStream(fullPath, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }

                        plat.ImagePath = imagePath;
                    }
            else{
                        plat.ImagePath = _context.Plats.AsNoTracking().FirstOrDefault(p => p.Id == plat.Id)?.ImagePath;
                    }

                    _context.Update(plat);
                    var existingIngredients = _context.PlatIngredients.Where(pi => pi.PlatId == plat.Id).ToList();
                    _context.PlatIngredients.RemoveRange(existingIngredients);
                    foreach (var ingredientId in plat.IngredientIds)
                    {
                        var platIngredient = new PlatIngredient
                        {
                            PlatId = plat.Id,
                            IngredientId = ingredientId,
                            Quantity = 1
                        };
                        _context.PlatIngredients.Add(platIngredient);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlatExists(plat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            if (!ModelState.IsValid)
            {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage); 
                }
            }
            return View(plat);
        }

        // GET: Plats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plat = await _context.Plats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (plat == null)
            {
                return NotFound();
            }

            return View(plat);
        }

        // POST: Plats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plat = await _context.Plats.FindAsync(id);
            if (plat != null)
            {
                _context.Plats.Remove(plat);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlatExists(int id)
        {
            return _context.Plats.Any(e => e.Id == id);
        }
    }
}

restaurant/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using restaurant.Data;
using restaurant.Models;

namespace restaurant.Controllers
{
    [Authorize]
    public class TablesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<Users> _userManager;

        public TablesController(AppDbContext context, UserManager<Users> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Tables
        [Authorize(Roles = "Admin,Client")]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            if (await _userManager.IsInRoleAsync(user, "Admin"))
                return View(await _context.Tables.ToListAsync());
            else { return View("ListTables", await _context.Tables.ToListAsync()); }
        }




        [Authorize(Roles = "Admin")]
        // GET: Tables/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var table = await _context.Tables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        // GET: Tables/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Status,PeopleNumber")] Table table)
        {
            if (ModelState.IsValid)
            {
                _context.Add(table);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(table);
        }
        [Authorize(Roles = "Admin")]
        // GET: Tables/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var table = await _context.Tables.FindAsync(id);
            if (table == null)
            {
                return NotFound();
            }
            return View(table);
        }

        // POST: Tables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Status,PeopleNumber")] Table table)
        {
            if (id != table.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(table);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TableExists(table.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(table);
        }

        [Authorize(Roles = "Admin")]
        // GET: Tables/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var table = await _context.Tables
                .FirstOrDefaultAsync(m => m.Id == id);
            if (table == null)
            {
                return NotFound();
            }

            return View(table);
        }

        // POST: Tables/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var table = await _context.Tables.FindAsync(id);
            if (table != null)
            {
                _context.Tables.Remove(table);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TableExists(int id)
        {
            return _context.Tables.Any(e => e.Id == id);
        }
    }
}

restaurant/Views/Shared/LoginPartiel.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<Users> SignInManager;

restaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - restaurant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/restaurant.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">restaurant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

restaurant/Views/Shared/_layoutDashUser.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Users> SignInManager
@inject UserManager<Users> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Gabarito&display=swap" rel="stylesheet">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/layoutDash.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/@(ViewData["Title"]).css" asp-append-version="true">



</head>
<body>
    <div class="sidebar">
        <div class="logo">
            <img src="~/images/eclipseKitchen1.png" alt="Logo">

        </div>
        <ul>

            <li>
                <a asp-controller="Reservations" asp-action="Index">
                    <i class="fa-solid fa-calendar"></i>
                    <span>Reservation</span>
                </a>
            </li>


            <li>
                <a asp-controller="Commandes" asp-action="Index">
                    <i class="fa-solid fa-box"></i>
                    <span>Commande</span>
                </a>
            </li>

            <li>
                <a asp-controller="Profils" asp-action="Index">
                    <i class="fa-regular fa-user"></i>
                    <span>Profil</span>
                </a>
            </li>


            <li class="logout">
                <a asp-controller="Account" asp-action="Logout">

                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span>Deconnecter</span>
                </a>
            </li>
        </ul>
    </div>

    <div class="main_content">
        <div class="header_nav">
            <div class="header_title">
                <span class="headerPageTitle"></span>
            </div>
            <div class="user_info">
                <span></span>
                <span></span>
            </div>
        </div>


        <div class="content">
            @RenderBody()
        </div>
    </div>

</body>
</html>

restaurant/Views/Shared/_layoutDashboard.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Users> SignInManager
@inject UserManager<Users> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Gabarito&display=swap" rel="stylesheet">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/layoutDash.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/@(ViewData["Title"]).css" asp-append-version="true">

   
    
</head>
<body>
    <div class="sidebar">
        <div class="logo">
            <img src="~/images/eclipseKitchen1.png" alt="Logo">

        </div>
        <ul>
            @if (User.IsInRole("Admin"))
            {
                <li class="active">
                    <a asp-controller="Apercus" asp-action="Index">
                        <i class="fas fa-tachometer-alt"></i>
                        <span>Aperçu</span>
                    </a>
                </li>

                <li>
                    <a asp-controller="Serveurs" asp-action="Index">
                        <i class="fa-solid fa-user"></i>
                        <span>Serveur</span>
                    </a>
                </li>

                <li>
                    <a asp-controller="Tables" asp-action="Index">
                        <i class="fa-solid fa-chair"></i>
                        <span>Table</span>
                    </a>
                </li>




                <li>
                    <a asp-controller="Plats" asp-action="Index">
                        <i class="fa-solid fa-list"></i>
                        <span>Plat</span>
                    </a>
                </li>

                <li>
                    <a asp-controller="Ingredients" asp-action="Index">
                    <i class="fa-solid fa-carrot"></i>
                    <span>Ingredient</span>
                </a>
            </li>

            }

            <li>
                <a asp-controller="Reservations" asp-action="Index">
                    <i class="fa-solid fa-calendar"></i>
                    <span>Reservation</span>
                </a>
            </li>


            <li>
                <a asp-controller="Commandes" asp-action="Index">
                    <i class="fa-solid fa-box"></i>
                    <span>Commande</span>
                </a>
            </li>

            <li>
                <a asp-controller="Profils" asp-action="Edit">
                    <i class="fa-solid fa-user"></i>
                    <span>Profil</span>
                </a>
            </li>


            <li class="logout">
                <a asp-controller="Account" asp-action="Logout">

                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span>Deconnecter</span>
                </a>
            </li>
        </ul>
    </div>

    <div class="main_content">
        <div class="header_nav">
            <div class="header_title">
                <span class="headerPageTitle"></span>
            </div>
            <div class="user_info">
                <span></span>
                <span></span>
            </div>
        </div>
   

    <div class="content">
            @RenderBody()
        </div>
    </div>

</body>
</html>

restaurant/Views/Shared/_layoutMain.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Users> SignInManager
@inject UserManager<Users> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eclipse kitchen</title>
    <link rel="stylesheet" href="~/css/StyleMain.css" asp-append-version="true">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Gabarito:wght@400..900&display=swap" rel="stylesheet">
</head>
<body>

    <div class="navbar">
        <div class="logo">
            <img src="~/images/eclipseKitchen.png" alt="Logo" height="50" width="50">
        </div>
        <div class="links">
            <ul>
                <li><a asp-controller="Home">Accueil</a></li>
                <li><a asp-controller="Menu" asp-action="Index">Menu</a></li>
                <li><a asp-controller="Tables" asp-action="Index">Table</a></li>
                <li><a asp-controller="Contact">Contactez-nous</a></li>
            </ul>
        </div>
        <div class="action-buttons">
            @if (!SignInManager.IsSignedIn(User))
            {
                <div class="action-buttons">
                <button>
                    <a asp-controller="Account" asp-action="Login">Login</a>
                </button>
                <button>
                    <a asp-controller="Account" asp-action="Register">Register</a>
                </button>
                </div>
            }
            else
            {
               <div class="actionLoggin">
                    @if (!User.IsInRole("Admin"))
                    {
                        <a asp-controller="Panier" asp-action="Index">
                            <i class="fa-solid fa-cart-shopping"></i>
                        </a>
                    }
               
                
                <div class="dropdown">
                    <i class="fa-solid fa-user user-icon"></i>
                    <div class="dropdown-menu">
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-controller="Apercus" asp-action="Index"><i class="fa-solid fa-file-invoice"></i><span>Account</span></a>
                            }
                            else
                            {
                                <a asp-controller="Commandes" asp-action="Index"><i class="fa-solid fa-file-invoice"></i><span>Account</span></a>
                            }
                            
                        <a asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-right-from-bracket"></i><span>Logout</span></a>
                    </div>
                </div>
                </div>
            }
        </div>
    </div>

    @RenderBody();

</body>
</html>

restaurant/Views/Shared/_layoutUsers.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Users> SignInManager
@inject UserManager<Users> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/@(ViewData["Title"]).css" asp-append-version="true">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css' rel='stylesheet'>

    <link href="https://fonts.googleapis.com/css2?family=Gabarito:wght@400..900&display=swap" rel="stylesheet">
</head>
<body>

    <div class="navbar">
        <div class="logo">
            <img src="~/images/eclipseKitchen.png" alt="Logo" height="50" width="50">
        </div>
        <div class="links">
            <ul>
                <li><a asp-controller="Home" asp-action="Index">Accueil</a></li>
                <li><a asp-controller="Menu" asp-action="Index">Menu</a></li>
                <li><a asp-controller="Tables" asp-action="Index">Table</a></li>
                <li><a href="">Contactez-nous</a></li>
            </ul>
        </div>
       
            <div class="action-buttons">
            @if (!SignInManager.IsSignedIn(User))
            {
                <button>
                    <a asp-controller="Account" asp-action="Login">Login</a>
                </button>
                <button>
                    <a asp-controller="Account" asp-action="Register">Register</a>
                </button>
            }
            else
            {
                @if (!User.IsInRole("Admin"))
                {
                    <a asp-controller="Panier" asp-action="Index">
                        <i class="fa-solid fa-cart-shopping"></i>
                    </a>
                }


                <div class="dropdown">
                    <i class="fa-solid fa-user user-icon"></i>
                    <div class="dropdown-menu">
                        <a asp-controller="Commandes" asp-action="Index"><i class="fa-solid fa-file-invoice"></i><span>Account</span></a>
                        <a asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-right-from-bracket"></i><span>Logout</span></a>
                    </div>
                </div>

            }
        </div>
       
    </div>

    
        

        @RenderBody()

        
    


    </body>
</html>